/*! Copyright © 2015, 2016, Oracle and/or its affiliates. All rights reserved. */
/*! mmapi v1.14 */
/*v1.14.0.3*/
/*Please do not modify this file except configuration section at the bottom.*/
(function(c,E){function m(a,b){return typeof a===b}function B(a){return m(a,"undefined")}function y(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function C(a,b){return y(a,b)&&m(a[b],"string")}function K(a,b,e){try{m(a,"function")&&a.apply(b,e)}catch(k){O&&O.log(k)}}function h(a,b){for(var e in a)y(a,e)&&b(a[e],e)}function L(a){var b=new Date;b.setTime(b.getTime()+864E5*a);return b}function J(a){function b(){for(var a=document.cookie.split(/;\s+/g),b={},e=0;e<a.length;e++){var c=a[e].split(/;|=/);
1<c.length&&(b[c[0]]=c[1])}return b}var e=this,c=a.domain,m=a.secure,n=encodeURIComponent,v=decodeURIComponent;e.set=function(a,b,v,h){h||(b=n(b));a=n(a)+"="+b+";domain="+c+";path=/"+(v?";expires="+L(v).toGMTString():"")+(m?";secure":"");document.cookie=a;return e};e.remove=function(a){e.set(a,"",-1);return e};e.removeAll=function(a){if(a){var c=b();h(c,function(b,c){(new RegExp("^"+a)).test(c)&&e.remove(v(c))})}};e.get=function(a,b){a=new RegExp("(?:^|; )"+n(a).replace(/([.$?*|{}()\[\]\\\/+^])/g,
"\\$1")+"=([^;]+)");a=document.cookie.match(a);if(!a)return E;a=a[1];return b?a:v(a)};e.getAll=function(a,e){if(a){var c=b(),k={};h(c,function(b,c){(new RegExp("^"+a)).test(c)&&(k[v(c)]=e?b:v(b))});return k}}}function aa(a){function b(a){a=JSON.parse('{"v":'+a+"}");return"v"in a?a.v:a}if(!/^((cookie-key-value)|(cookie-key-value-secure))$/.test(a.type))throw"(mm module: storage) Invalid storage type: "+a.type;var c="cookie-key-value-secure"===a.type,k=a.cprefix+"."+(a.namespace||"def")+".",m=k.replace(/\./g,
"\\."),n=new J({domain:a.domain,secure:c});this.get=function(a){if(!a){a=n.getAll(m);var c=k.length,e={};h(a,function(a,h){e[h.substring(c)]=b(a)});return e}return(a=n.get(k+a))?b(a):a};this.set=function(a,b,c){null===b||B(b)?n.remove(k+a):(b=JSON.stringify({v:b}),b=b.substring(5,b.length-1),n.set(k+a,b,B(c)?0:c));return this};this.removeAll=function(){n.removeAll(m);return this};this.testStorage=function(){var a=(""+Math.random()).substring(0,5);n.set(k+"tst",a,10);a=n.get(k+"tst",!0)===a?1:0;n.remove(k+
"tst");return a}}function ba(a){function b(a,b){var c={};h(a,function(a,b){c[b]=a});h(b,function(a,b){c[b]=a});return c}function c(a){for(var b={},c="",e=0,r;r=A.get(a+e++,!0);)c+=r;c=decodeURIComponent(c);try{b=JSON.parse(c)}catch(P){}return b}function k(){q=c(C);x=c(E);y();q[t]=q[t]||{};x[t]=x[t]||{}}function m(a,b,c){b=JSON.stringify(b);var e="{}"===b,r=0;for(b=encodeURIComponent(b);A.get(a+r,!0);)A.remove(a+r++);if(!e)for(r=0;e=b.substr(3E3*r,3E3);)A.set(a+r++,e,B(c)?365:c,!0)}function n(){m(C,
q);m(E,x,0)}function v(a){var b={};h(a,function(a,c){b[c]=H(a).v});return b}function y(){var a=(new Date).getTime(),b=q[t];h(b,function(c,e){H(c).e<=a&&delete b[e]});n()}function H(a){var b=a.indexOf("|");return{v:JSON.parse(a.substring(b+1,a.length)),e:a.substring(0,b)}}if(!/^((cookie)|(cookie-secure))$/.test(a.type))throw"(mm module: storage) Invalid storage type: "+a.type;var q,x,z=a.cprefix+".",C=z+"store.p.",E=z+"store.s.",A=new J({domain:a.domain,secure:"cookie-secure"===a.type}),t=a.namespace||
"def";this.get=function(a){k();var c=b(q[t],x[t]);return a?c[a]?H(c[a]).v:c[a]:v(c)};this.set=function(a,b,c){k();var e=q[t],h=x[t];delete e[a];delete h[a];null===b||B(b)||(c?(b=L(c).getTime()+"|"+JSON.stringify(b),e[a]=b):h[a]="0|"+JSON.stringify(b));n();return this};this.removeAll=function(){k();q[t]={};x[t]={};n();return this};this.testStorage=function(){var a=(""+Math.random()).substring(0,5);A.set(z+"tst",a,10);a=A.get(z+"tst",!0)===a?1:0;A.remove(z+"tst");return a};this.exportData=function(){k();
var a={};h(q,function(b,c){a[c]=b});h(x,function(c,e){a[e]=b(a[e],c)});h(a,function(b,c){h(b,function(b,e){a[c][e]=H(b)})});return a};k()}if(!c.mmsystem){var O=c.console||{log:function(){},error:function(){}},T=new function(a){function b(a,f){if(D[a])for(var d=D[a].length-1;0<=d;d--)D[a][d].call({},f)}function e(a){F=m(a,"boolean")?a:!1}function k(a,f,b){b=b||{};b.type="text/javascript";b.id=a;b.src=f;if(F){a=document.getElementsByTagName("head")[0];var d=document.createElement("script");h(b,function(a,
f){d.setAttribute(f,a)});a.insertBefore(d,a.lastChild)}else{var c="";h(b,function(a,d){c+=" "+d+'="'+a+'"'});document.write("<script"+c+">\x3c/script>")}}function L(a){if(!m(a,"object"))return a;if(a.constructor===Array)return a.join(";");var d=[];h(a,function(a,f){a.constructor===Array?h(a,function(a){d.push(f+"="+a)}):d.push(f+"="+encodeURIComponent(a))});return d.join(";")}function n(a){a=a?U(a):{};var d={};m(a["mm-dlp-api"],"string")&&(d.fv={ref:a["original-ref"].substring(0,256),url:a["original-url"].substring(0,
1024)},d.origin=/http(s)?:\/\/.*?([^/]|$)+/.exec(d.fv.url)[0]);h(a,function(a,b){"mmcore."===b.substring(0,7)&&(d[b.substring(7)]=a)});return d}function v(){var d="mmRequestCallbacks["+I+"]",b={},e=c.screen;b.fv={dmn:a.domain,ref:document.referrer.substring(0,256),url:location.href.substring(0,1024),scrw:e.width,scrh:e.height,clrd:e.colorDepth,cok:u[p.persistent].testStorage()};b.lver="1.14";b.jsncl=d;b.ri=I;b.lto=-(new Date).getTimezoneOffset();b.jrt="inline"===a.executionMode?"f":"s";return b}function T(d,
b){var f=d&&d.Packages||[],l=f.length;if(0<l){c.mmInitCallback=function(a){a(g,d,{skipResponseProcessing:!0,skipPersistentData:!0,useLoaderStorage:!0,debug:ga});0===--l&&(b(),c.mmInitCallback=E)};for(var e=0;e<f.length;e++)k("mmpack."+e,0===f[e].indexOf("//")?f[e]:a.baseContentUrl+f[e])}else b()}function H(a){(a=document.getElementById(a))&&a.parentNode?a.parentNode.removeChild(a):a&&a.removeAttribute("src")}function q(a,f,e){a=(X[a-1]=f)&&f.PersistData||[];var d=f&&f.SystemData&&f.SystemData[0]&&
f.SystemData[0].ResponseId||0;if(d>=Y){for(var w=a.length;w--;)g.setParam(a[w].Name,a[w].Value,p.persistent,a[w].Expiration);Y=d}if(C(f,"mmcoreResponse")&&y(c,"mmcore"))try{Function(f.mmcoreResponse).call(c)}catch(W){O.log(W)}b("response",f);e(!!f);b("responseExecuted",f);F=!0}function x(a,b){var d="mmrequest."+I;(function(a,b){c.mmRequestCallbacks[a]=function(f){H(d);var e=!1,l=function(){e=!0;1===a?T(f,function(){q(a,f,b);var d=n(document.location.search).origin;d&&c.parent&&c.parent.postMessage&&
c.parent.postMessage(JSON.stringify({hash:"unhide",command:"unhide",data:{}}),d)}):q(a,f,b)};if(0!==M.length){for(var w=0;w<M.length;w++)M[w](f,l);e||(F=!0)}else l();delete c.mmRequestCallbacks[a]}})(I,b);k(d,a,{onerror:"window['mmRequestCallbacks']["+I+"](false);"});I++}function z(){var a={};return{get:function(b){return b?a[b]:a},set:function(b,d,c){0>parseInt(c)?delete a[b]:a[b]=d},removeAll:function(){a={}}}}function U(a){a=a.split(/\?|&/);for(var b={},d,c,e=0;e<a.length;e++)if(a[e]){d=a[e].split("=");
try{c=decodeURIComponent(d[1]||"")}catch(W){c=d[1]||""}b[d[0]]=c}return b}function fa(a){function b(a,b,f){var e;if(e=c[a]){d[a]=b;e=e.split(/;/);for(var l=0;l<e.length;l++){var w=e[l].split("=");(a=w[0].replace(/^\s+|\s+$/gm,""))&&f(b,a,w[1]||"")}}}var d={},c=U(a);N||(d.pageid=c.pageid);d.jsver=c.jsver;b("uv",{},function(a,b,d){y(a,b)||(a[b]=[]);a[b].push(d)});b("uat",{},function(a,b,d){a[b]=decodeURIComponent(d)});b("ids",{},function(a,b,d){d&&(a[b]=decodeURIComponent(d))});b("rul",[],function(a,
b,d){a.push(b)});return d}function A(){if(y(c,"mmcore")){var b=c.mmcore;b.server=a.srv;g.CGRequestInternal=g.CGRequest;g.CGRequest=function(a,d){N=!0;Q=a;R=d;b.CGRequest()};var f=b._Tag;b._Tag=function(d){if(-1==d.indexOf(a.srv))f.apply(b,arguments);else{b._Clear.call(b);var c=g.mergeParams(R,fa(d));Z=F;N||(F=b._async);g.CGRequestInternal(Q,c);F=Z;R=Q=E;N=!1}};var e=b.SetCookie;b.SetCookie=function(a){/^(mmid|pd|srv)$/.test(a)||e.apply(b,arguments)}}}function t(a){return a||c.location.hostname.replace(/^www\./i,
"")}function r(a,b,c){var d="";0<b.length&&"."!=b.substring(b.length-1)&&(d=".");b=b+d+c;d=a.get(b);m(d,"string")&&d&&(g.setParam(c,d,p.persistent,365),a.remove(b))}function V(a){var b=y(c,"mmcore")&&c.mmcore.cookie_domain?c.mmcore.cookie_domain:C(a,"mmcoreCookieDomain")?a.mmcoreCookieDomain:a.cookie_domain;a=y(c,"mmcore")&&c.mmcore.cprefix?c.mmcore.cprefix:C(a,"mmcoreCprefix")?a.mmcoreCprefix:a.cprefix+".";b=new J({domain:t(b)});r(b,a,"pd");r(b,a,"srv");r(b,"","mmid")}function ca(a){var b=g.getParam,
d=function(a,b,d,c){g.setParam(a,b,B(d)?1:d,c)};K(a.beforeInit,{},[b,d,{getParam:b,setParam:d,validateResponses:g.validateResponses,disable:function(){G[p.page].set("disabled",1)},setAsync:e}]);P()||(g.on("request",function(){K(a.beforeRequest,{},[b,d])}),g.on("response",function(c){K(a.afterResponse,{},[b,d,c])}),g.on("responseExecuted",function(c){K(a.afterResponseExecution,{},[b,d,c])}))}function da(a){c.mmcoreInitCallback=function(b){V(a);A();g.CGRequest(function(){m(b,"function")&&b.apply(c.mmcore,
arguments)},{});delete c.mmcoreInitCallback};"local"!==a.mmcoreUrl&&k("mmcoreIntegration",a.mmcoreUrl)}function ea(a,b){C(b,"un")&&(a=0===a.indexOf("http:")?a.substring(5):a,a=0===a.indexOf("//")?"https:"+a:a);return a}function P(){return 1==G[p.persistent].get("disabled")||1==G[p.page].get("disabled")}this.version="1.14";var g=this,X=[],I=1,F=!1,D={},ga={},u=[],G=[],p={persistent:0,deferredRequest:1,request:2,page:3},M=[],Y=0,Q,R,Z,N=!1,S=null!==a.storageType.match(/.*-secure$/);this.baseStorage=
function(){var b=t(a.cookie_domain),c=a.cprefix+"\\.store\\.p\\.",e=a.cprefix+"\\.store\\.s\\.";var l=function(c){return function(d){var e={p:"mmparams.p",d:"mmparams.d",e:"mmengine"};return new ba({type:c,namespace:e[d]?e[d]:d,domain:b,cprefix:a.cprefix})}};var g=function(c){return function(d){var e={"mmparams.p":"p","mmparams.d":"d",mmengine:"e"};return new aa({type:c,namespace:e[d]?e[d]:d,domain:b,cprefix:a.cprefix})}};if(a.storageType.match(/cookie-key-value($|-secure$)/)){var k=l("cookie");var n=
g(a.storageType);l=k().exportData();var p=!1;h(l,function(a,b){var c=n(b);h(a,function(a,b){p=!0;var d=a.e;d=(d=parseInt(d))?Math.round(Math.abs(((new Date).getTime()-d)/864E5)):d;c.set(b,a.v,0<=d?d:30)})});p&&(l=new J({domain:b,secure:S}),l.removeAll(c),l.removeAll(e));return n}k=l(a.storageType);n=g("cookie-key-value");l=new J({domain:b,secure:S});l=l.getAll(a.cprefix+"\\.",!0);var m={};h(l,function(a,b){var d=b.split(/\./);if(2<d.length&&"store"!=d[1]){a=m[d[1]];a||(a=n(d[1]),m[d[1]]=a);var c=
k(d[1]);b=b.substring((d[0]+"."+d[1]+".").length);a=a.get(b);c.set(b,a,30)}});h(m,function(a){a.removeAll()});return k}();this.baseStorage.storeStrategy=p;this.baseStorage.isSecure=S;this.mergeParams=function(a,b){a=B(a)?{}:a;b=B(b)?{}:b;if(!m(b,"object"))return b;var d={};m(a,"object")&&h(a,function(a,b){d[b]=a});h(b,function(a,c){d[c]=d[c]?d[c].constructor===Array&&b[c].constructor===Array?d[c].concat(a):g.mergeParams(d[c],a):a});return d};this.CGRequest=function(d,e){d=d||function(){};e=e||{};
c.mmRequestCallbacks=c.mmRequestCallbacks||{};b("request");var f=g.mergeParams(v(),g.mergeParams(g.mergeParams(u[p.persistent].get(),g.mergeParams(u[p.deferredRequest].get(),g.mergeParams(u[p.page].get(),u[p.request].get()))),n(location.search))),l=[];e=g.mergeParams(f,e);h(e,function(a,b){l.push(encodeURIComponent(b)+"="+encodeURIComponent(L(a)))});u[p.deferredRequest].removeAll();u[p.request].removeAll();e=ea(a.srv,e);x(e+l.join("&"),d);return this};this.getResponses=function(){return X};this.setParam=
function(a,b,c,e){u[c].set(a,b,B(e)?365:e);return this};this.getParam=function(a,b){return u[b].get(a)};this.removeParam=function(a,b){u[b].set(a,"",-1);return this};this.on=function(a,b){D[a]&&D[a].push(b);return g};this.disable=function(){G[p.persistent].set("disabled",1,0);return this};this.enable=function(){G[p.persistent].set("disabled",null,-1);return this};this.validateResponses=function(a){m(a,"function")&&M.push(a)};(function(a){function b(){ca(a);P()||(C(a,"mmcoreUrl")&&a.mmcoreUrl?da(a):
(V(a),g.CGRequest(E,{})))}h(a,function(a,b){g[b]=a});var d=n(document.location.search);if(1!=d.disabled){g.calcCookieDomain=t(g.cookie_domain);e(a.async);G[p.persistent]=g.baseStorage("ls");G[p.page]=z();u[p.persistent]=g.baseStorage("p");u[p.deferredRequest]=g.baseStorage("d");u[p.request]=z();u[p.page]=z();D.request=[];D.response=[];D.responseExecuted=[];var l=n(document.referrer).pruh,d=d.pruh,m=c.mmpruh,q=g.getParam("pruh",0),r=(l?l+",":"")+(d?d+",":"")+(m?m+",":"")+(q?q:"");r?(c.mmInitCallback=
function(a){a(g,r,b)},k("MM.PRUH",a.baseContentUrl+"utils/pruh.js")):b()}})(a);return this}({
 storageType:'cookie',
 cprefix:'mmapi',
 domain:'lesmills.com',
 baseContentUrl:'//service.maxymiser.net/platform/us/api/',
 cookie_domain:location.hostname.match(/^[\d.]+$|/)[0] || ('.' + (location.hostname.match(/[^.]+\.(\w{2,3}\.\w{2}|\w{2,})$/) || [location.hostname])[0]),
 srv:'//service.maxymiser.net/cg/v5us/?',
 async:false,
 mmcoreUrl:'',
 mmcoreCookieDomain:'',
 mmcoreCprefix:'',
 beforeInit:function( getParam, setParam, loader ){ },
 beforeRequest:function( getParam, setParam ){ },
 afterResponse:function( getParam, setParam, genInfo ){ },
 afterResponseExecution:function( getParam, setParam, genInfo ){ }
});c.mmsystem=new function(a){this.enableUtility=function(b){var c=a.getParam("un",a.baseStorage.storeStrategy.persistent)||"";(new RegExp("(^|,)"+
b+"($|,)")).test(c)||(c=c.split(","),c.push(b),a.setParam("un",c.join(",").replace(/(^,)|(,$)/g,""),a.baseStorage.storeStrategy.persistent));return this};this.disableUtility=function(b){var c=a.getParam("un",a.baseStorage.storeStrategy.persistent)||"";(new RegExp("(^|,)"+b+"($|,)")).test(c)&&(c=c.replace(new RegExp("(^|,)"+b+"($|,)","gi"),",").replace(/(^,)|(,$)/g,""),a.setParam("un",c,a.baseStorage.storeStrategy.persistent));return this};this.enable=function(){a.enable();return this};this.disable=
function(){a.disable();return this};this.getConfig=function(){return{storageType:a.storageType,cprefix:a.cprefix,domain:a.domain,baseContentUrl:a.baseContentUrl,cookie_domain:a.cookie_domain,srv:a.srv,async:a.async,beforeInit:a.beforeInit,beforeRequest:a.beforeRequest,afterResponse:a.afterResponse,afterResponseExecution:a.afterResponseExecution}}}(T)}})(window);
